[package]
name = "erwin"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29"
egui = "0.29"
serde_json = "1.0"
log = "0.4"
env_logger = "0.10"
anyhow = "1.0"
rfd = "0.11"

[dependencies.serde]
version = "1.0"
features = [ "derive",]
